-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, 
       SUM(BOOK.PRICE*SALES.SALES) AS TOTAL_SALES
  FROM BOOK
  LEFT JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
  LEFT JOIN BOOK_SALES SALES ON BOOK.BOOK_ID = SALES.BOOK_ID
 WHERE SALES.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
 GROUP BY AUTHOR.AUTHOR_NAME, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
 ORDER BY AUTHOR.AUTHOR_ID ASC, BOOK.CATEGORY DESC;