-- 코드를 입력하세요
SELECT BOOK.BOOK_ID BOOK_ID, AUTHOR.AUTHOR_NAME AUTHOR_NAME, BOOK.PUBLISHED_DATE PUBLISHED_DATE
  FROM BOOK
  LEFT JOIN AUTHOR
    ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
 WHERE BOOK.CATEGORY = '경제'
 ORDER BY BOOK.PUBLISHED_DATE ASC